edsm/views/home.py
from flask import Blueprint, render_template, session
# from ..util.database import sql_single_request

home_blueprint = Blueprint('home', __name__, template_folder='templates')


@home_blueprint.route('/')
def home():
    sql = "SELECT * FROM edsm.systemswithcoordinates WHERE name='Sol';"
    # result = sql_single_request(sql)
    if 'username' in session:
        return render_template('home.html', title='Home')
    else:
        return "NOT LOGGED IN"


@home_blueprint.route('/home2')
def home2():
    sql = "SELECT * FROM edsm.systemswithcoordinates WHERE name='Sol';"
    # result = sql_single_request(sql)
    return render_template('home2.html', title='Home')

edsm/views/login.py
# ==========
# File : login.py
# Author : Jb
# First created on : 23/10/2018
# Description: Login view
# ==========

from flask import Blueprint, render_template, redirect, url_for, session
from ..forms import EmailPasswordForm
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class User(db.Model):
    __tablename__ = 'user'

    email = db.Column(db.String, primary_key=True)
    password = db.Column(db.String)
    authenticated = db.Column(db.Boolean, default=False)

    def is_active(self):
        """True, as all users are active."""
        return True

    def get_id(self):
        """Return the email address to satisfy Flask-Login's requirements."""
        return self.email

    def is_authenticated(self):
        """Return True if the user is authenticated."""
        return self.authenticated

    def is_anonymous(self):
        """False, as anonymous users aren't supported."""
        return False


login_blueprint = Blueprint('login', __name__, template_folder='templates')


@login_blueprint.route('/', methods=["GET", "POST"])
def login():
    form = EmailPasswordForm()
    res=''
    if form.validate_on_submit():
        # Todo: Add action to form after validation
        res = form.email.data
        session['username'] = res
        return redirect(url_for('home.home'))
        # return redirect(url_for('home_blueprint'))
    return render_template('login.html', title='Login', form=form, res=res)

edsm/views/sphere2riches.py
# ==========
# File : sphere2riches.py
# Author : Jb
# First created on : 24/10/2018
# Description: Sphere2Riches blueprint file
# ==========

from datetime import datetime
from operator import itemgetter
from flask import Blueprint, render_template, request, redirect, url_for
from ..forms import Sphere2RichesForm
from ..util.misc import http_request, urlify, req_value, appstop
from ..util.database import sql_single_request, update_row, db


sphere2riches_blueprint = Blueprint('sphere2riches', __name__, template_folder='templates')


def find_systems(sysName, minRadius, radius, valueLimit = None, maxOutput = None):
    results = []
    api_url = "https://www.edsm.net/api-v1/sphere-systems?systemName=" + urlify(sysName) + "&minRadius=" + str(
        minRadius) + "&radius=" + str(
        radius) + "&showId=1&showCoordinates=1"
    api_data = http_request(api_url).json()
    print("======================================\nSystems Found : " + str(len(api_data)))
    for system in api_data:
        print("======================================")
        sys_dict = {'name': system['name'], 'value': '', 'dist': system['distance'], 'id': system['id']}
        edsm_url = "https://www.edsm.net/en_GB/system/id/" + str(system['id']) + "/name/" + urlify(system['name'])

        # Mark: Check if system is in database
        sql = "SELECT value FROM edsm.systemswithcoordinates WHERE edsm_id=" + str(system['id']) + " LIMIT 10"
        print("Looking for system...")
        sql_req = sql_single_request(sql)
        if sql_req is None:
            sql_req = 0
        else:
            sql_req = list(filter(None, sql_req))
        # Debug: Search Query functional
        # results = str(sql_req)

        # Search found something
        if sql_req:
            value = sql_req[0]
            # Value has been filled & known
            if value > 1:
                print("Value Found !\nID : " + str(system['id']) + " | Value : " + str(sql_req[0]))
                sys_dict['value'] = value
                if valueLimit is not None:
                    if sys_dict['value'] > valueLimit:
                        results.append(sys_dict)
            # Value is empty
            else:
                print("Value not known")
                if req_value(edsm_url) is not None:
                    sys_dict['value'] = req_value(edsm_url)
                    results.append(sys_dict)
                    sql = "UPDATE edsm.systemswithcoordinates SET value=" + str(sys_dict['value']) + \
                          " WHERE edsm_id=" + str(sys_dict['id'])
                    update_row(sql)
                    print(sys_dict)

        # Search found nothing
        else:
            print("System not found in db")
            # No value found in EDSM
            if req_value(edsm_url) is not None:
                print(req_value(edsm_url))
                sys_dict['value'] = int(req_value(edsm_url))
                time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                sql = "REPLACE INTO edsm.systemswithcoordinates SET edsm_id=" + str(sys_dict['id']) + ", name='" + \
                      str(sys_dict["name"]) + "', date='" + time + "', coordX=" + str(system['coords']['x']) + \
                      ", coordY=" + str(system['coords']['y']) + ", coordZ=" + str(system['coords']['z']) + \
                      ", value=" + str(sys_dict['value']) + ";"
                update_row(sql)
                print('New system saved !')
                if valueLimit is not None:
                    if sys_dict['value'] > valueLimit:
                        results.append(sys_dict)
            else:
                time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                sql = "REPLACE INTO edsm.systemswithcoordinates SET edsm_id=" + str(sys_dict['id']) + ", name='" + \
                      str(sys_dict["name"]) + "', date='" + time + "', coordX=" + str(system['coords']['x']) + \
                      ", coordY=" + str(system['coords']['y']) + ", coordZ=" + str(system['coords']['z']) + \
                      ", value=" + str(1) + ";"
                update_row(sql)
                print("Value not known... Value set to 1")
    results = sorted(results, key=itemgetter('value'), reverse=True)
    results = [{'name': 'Name', 'value': 'Value', 'dist': 'Distance'}]+results
    print("\n////////////////////\n===== RESULTS =====")
    return results


@sphere2riches_blueprint.route('/', methods=["GET", "POST"])
def sphere2riches():
    form = Sphere2RichesForm()
    res = ''
    src = ''
    if form.validate_on_submit():
        # Todo: Add action to form after validation
        res = find_systems(form.name.data, form.minRadius.data, form.maxRadius.data, valueLimit=form.valueLimit.data)
        # return redirect(url_for('home_blueprint'))
    return render_template('sphere2riches.html', title='Sphere - 2 - Riches', form=form, res=res, src=src)


@sphere2riches_blueprint.route('/exit', methods=["GET", "POST"])
def appexit():
    appstop()

edsm/templates/home.html
{% extends "layout.html" %}
{% block assets %}
    {% assets "home_css" %}
            <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{#{% block heading %}#}
{#<h1>Welcome Commander</h1>#}
{#{% endblock %}#}

{% block body %}

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-3"></div>
            <div class="col-auto" id="login-card">
                <img id="ED-logo" src="../static/img/svg/Logos/ED-Logo-Orange.svg" alt="Elite Dangerous Logo">
                <div class="row justify-content-center">
                    <button type="button" class="std-button">Login</button>
                </div>
                <div class="row justify-content-center">
                    <button type="button" class="std-button">Sign Up</button>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
    </div>

{% endblock %}

edsm/templates/home2.html
{% extends "layout.html" %}
{% block assets %}
    {% assets "home_css" %}
            <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{% block heading %}
<h1>Welcome Commander</h1>
{% endblock %}

{% block body %}
{#    <p>{{ result }}</p>#}

    <a href="{{ url_for('login.login') }}">Login</a>
    <br>
    <a href="{{ url_for('sphere2riches.sphere2riches') }}">Sphere2Riches</a>

{#    <div class="alert alert-primary" role="alert">#}
{#        A simple primary alert—check it out!#}
{#    </div>#}

{% endblock %}

edsm/templates/layout.html
<html>
<head>
    <title>{{ title }}</title>
    {% block assets %}
    {%  endblock %}
</head>
<body>

{# Mark: Navbar #}
<div class="navbar navbar-dark">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="{{ url_for('home.home') }}">Navbar</a>
    <!-- Collapse button -->
    <button></button>
</div>

<div class="body-content">
{# Mark: Heading #}
{% block heading %}
{% endblock %}

{# Mark: Body #}
{% block body %}
        <p>Empty <code>body</code> block !!</p>
{% endblock %}
</div>
</body>

{# Mark: Scripts #}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="../static/js/modernizr-custom.js"></script>
<script src="../static/js/scripts.js"></script>
{% block scripts %}
{% endblock %}
</html>

edsm/templates/login.html
{% extends "layout.html" %}

{% block body %}
    <form action="{{ url_for('login.login') }}" method="post">
        {{ form.email.label }} - {{ form.email(placeholder = 'tes@tes.com', class_ = 'email') }}
        <br>
        {{ form.password.label }} - {{ form.password }}
        {{ form.csrf_token }}
        <button type="submit">Log In !</button>
    </form>

    <p>{{ res }}</p>
{% endblock %}

edsm/templates/sphere2riches.html
{% extends 'layout.html' %}

{% block assets %}
    {% assets "s2r_css" %}
            <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{% block heading %}
<h1>Sphere - 2 - Riches</h1>
{% endblock %}

{% block body %}
{#    <div class="row">#}
{#        <form action="" method="post" class="col">#}
{#                <div class="row name">#}
{#                    {{ form.name.label }} - {{ form.name(placeholder = 'Sol', class_ = 'sysName') }}#}
{#                </div>#}
{#                <div class="row minRadius">#}
{#                    {{ form.minRadius.label }} - {{ form.minRadius }}#}
{#                </div>#}
{#                <div class="row maxRadius">#}
{#                    {{ form.maxRadius.label }} - {{ form.maxRadius }}#}
{#                </div>#}
{#                <div class="row valueLmit">#}
{#                    {{ form.valueLimit.label }} - {{ form.valueLimit }}#}
{#                </div>#}
{##}
{#            {{ form.csrf_token }}#}
{##}
    {#        <button type="submit" class="std-button">Find $$$</button>#}
{#                <div class="row">#}
{#                    <button type="submit" class="button button--aylen button--text-thick button--border-thin">Find $$$</button>#}
{#                </div>#}
{#        </form>#}
{#    </div>#}
    <div class="row">
        <div class="col-4">
            <form action="" method="post">
                <div class="form-group row">
                    {{ form.name.label(for = 'name', class_='col-4') }}
                    {{ form.name(placeholder = 'Sol', class_ = 'sysName col-8', id='name') }}
                </div>
                <div class="form-group row">
                    {{ form.minRadius.label(for = 'minRadius', class_='col-4') }}
                    {{ form.minRadius(id='minRadius', class_ = 'col-8') }}
                </div>
                <div class="form-group row">
                    {{ form.maxRadius.label(for = 'maxRadius', class_='col-4') }}
                    {{ form.maxRadius(id='maxRadius', class_ = 'col-8') }}
                </div>
                <div class="form-group row">
                    {{ form.valueLimit.label(for = 'valueLimit', class_='col-4') }}
                    {{ form.valueLimit(id='valueLimit', class_ = 'col-8') }}
                </div>
                {{ form.csrf_token }}
                <div class="form-group row">
                    <button id="s2r-submit" type="submit" class="button button--aylen button--text-thick button--border-thin">Find $$$</button>
                    <div id="loader"></div>
                </div>
            </form>
        </div>
        <div class="col-8">
            <table class="table">
                 <thead class="thead-light">
                    {% for result in res %}
                        {% if result == res[0] %}
                                <tr>
                                    <th scope="col">{{ result['name'] }}</th>
                                    <th scope="col">{{ result['value'] }}</th>
                                    <th scope="col">{{ result['dist'] }}</th>
                                </tr>
                        {% endif %}
                    {% endfor %}
                 </thead>
                <tbody>
                    {% for result in res %}
                        {% if result != res[0] %}
                            <tr>
                                <td scope="row">{{ result['name'] }}</td>
                                <td>{{ result['value'] }}</td>
                                <td>{{ result['dist'] }}</td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <a href="./exit" style='font-family: "Eurocaps";font-size: 20px;font-weight: bold'>EXIT</a> <- End program FOREVEEEEER ☠️☠️☠️


{% endblock %}

{% block scripts %}
    <script src="../static/js/s2r.js"></script>
{% endblock %}